[package]
name = "tok-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2"
serde_json = "1"
regex = "1.10"
rustls = "0.23"
webpki-roots = "0.26"

[lib]
crate-type = ["staticlib", "rlib"]
